// src/components/Navbar.vue
<template>
  <nav class="grid grid-cols-5 gap-2 mb-1">
    <div class="col-span-1">
      <span
        id="title"
        class="hidden sm:inline-block"
      >
        Juno Hosting
      </span>
    </div>
    <div class="col-span-4">
      <ul class="flex float-right">
        <li>
          <router-link to="/">
            Home
          </router-link>
        </li>
        <li>
          <router-link to="/about">
            About
          </router-link>
        </li>
        <li>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://vps.junohosting.net"
          >
            Web Panel
          </a>
        </li>
        <li>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://discord.gg/asfmaXr"
          >
            Discord
          </a>
        </li>
      </ul>
    </div>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'Navbar',
  data: () => ({
    open: false
  })
})
</script>

<style lang="postcss" scoped>
nav {
  @apply
    rounded
    bg-gray-200
    py-2 px-2;
}

ul li * {
  @apply
    mr-3
    inline-block
    rounded
    text-blue-500
    py-1 px-3;
}

ul li *:hover, ul li a:focus {
  @apply bg-gray-300;
}

#title {
  font-family: 'Permanent Marker';
  @apply
    ml-3
    font-bold
    text-lg;
}
</style>

// components/navbar.tsx
import Link from 'next/link'

const entries: {
  href: string;
  label: string;
  local: boolean;
}[] = [
  { href: '/', label: 'Home', local: true },
  { href: 'https://billing.junohosting.net', label: 'Client Area', local: false },
  { href: 'https://discord.gg/asfmaXr', label: 'Contact Us', local: false }
]

export default function Navbar () {
  return (
    <nav className="grid grid-cols-5 gap-2 mb-1 p-3">
      <div className="col-span-1">
        <span
          id="title"
          className="mr-3 inline-block font-bold py-1 text-gray-900 px-3"
        >
          Juno Hosting
        </span>
      </div>
      <div className="col-span-4">
        <ul className="flex float-right">
          {entries.map(({ href, label, local }) => {
            return (
              <li
                className="mr-3 inline-block font-semibold py-1 px-3"
                key={label}
              >
                {local
                  ? (
                      <Link href={href}>
                        <a className="text-indigo-600 hover:underline">
                          {label}
                        </a>
                      </Link>
                    )
                  : (
                      <a className="text-indigo-600 hover:underline" href={href}>
                        {label}
                      </a>
                    )}
              </li>
            )
          })}
        </ul>
      </div>
    </nav>
  )
}
